# Generated by Django 4.1.3 on 2024-06-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_alter_event_date_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
